# Generated by Django 3.1.3 on 2020-12-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201214_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='question',
        ),
    ]
